---
format:
  revealjs: 
    theme: [default, slide-styles.scss]
    width: 1280
    height: 720
    include-after-body: 
      - "all-the-js-code.html"
echo: false
code-line-numbers: false
---

## Quarto Websites: Welcome!

Wifi:

Find the slides at: 

Verify the pre-work steps: 

Join the Discord: #workshop-quarto-websites

## Housekeeping

## Code of Conduct {.smaller}

## Breaks

Full schedule at:

| Time          |                                     |
|---------------|-------------------------------------|
| 10:30 - 11:00 | *Coffee Break*                      |
| 12:30 - 13:30 | *Lunch*                             |
| 15:00 - 15:30 | *Coffee Break*                      |
|         17:00 | END                                 |

## About Us

::: {.columns}
::: {.column}
### Charlotte Wickham

* Quarto user for 2+ years
* Quarto website user for 1.5+ years
* Statistics + R background

:::
::: {.column}
### Emil Hvitfeldt
:::
::: 

## About You 

**Your Turn**

Introduce yourself to your neighbors:

- Name
- Professional affiliation
- What do you use Quarto for?

## Meeting you where you are

- You've used Quarto for single documents

- You are comfortable editing, saving and previewing files in your IDE

- You want to build a website

## Why Quarto for Websites?

* You don't need to learn anything new for page content
* You get nice website features out of the box: GitHub links, social cards, navigation, etc.
* A lot of customization available via YAML options
* Customize style as much (or as little) as you want

## Our Goal

::: {.center}
You walk away with a website that reflects you both in content and style.
:::

## Our Goal

Along the way you'll learn how to:

* Use a template to get started quickly
* Create a landing page using `about` templates
* Use YAML options to customize the style of your website
* Add navigational elements to help visitors find your content
* Customize the appearance of your site with CSS and SCSS
* Generate lists of content automatically with listings

## Workshop structure

- My turn: Lecture segments + live coding

- Your Turn: Practice exercises for you

## How to get help?

* Raise your *color* post-it note

* Ask in Discord

* Talk to us during breaks or your-turns

# Let's jump in!



